"""empty message

Revision ID: e50d04ebe8e5
Revises: 
Create Date: 2020-02-19 00:12:07.160869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e50d04ebe8e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_project_id', sa.String(length=255), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('signature_date', sa.DateTime(timezone=255), nullable=True),
    sa.Column('service_commencement', sa.DateTime(timezone=255), nullable=True),
    sa.Column('contract_duration_month', sa.Integer(), nullable=True),
    sa.Column('contract_value_usd', sa.Numeric(), nullable=True),
    sa.Column('projected_margin_usd', sa.Numeric(), nullable=True),
    sa.Column('component_of_bespoke', sa.Integer(), nullable=True),
    sa.Column('often_provide_services', sa.Integer(), nullable=True),
    sa.Column('is_transition_plan', sa.Integer(), nullable=True),
    sa.Column('transition_plan_date', sa.DateTime(timezone=255), nullable=True),
    sa.Column('is_transition_charges', sa.Integer(), nullable=True),
    sa.Column('transition_charges', sa.Numeric(), nullable=True),
    sa.Column('milestones', sa.Integer(), nullable=True),
    sa.Column('payment_milestones', sa.Integer(), nullable=True),
    sa.Column('service_levels_without_credit', sa.Integer(), nullable=True),
    sa.Column('service_credit_cap', sa.Integer(), nullable=True),
    sa.Column('is_transformation_plan', sa.Integer(), nullable=True),
    sa.Column('transformation_plan_start', sa.DateTime(timezone=255), nullable=True),
    sa.Column('transformation_plan_end', sa.DateTime(timezone=255), nullable=True),
    sa.Column('service_levels_with_credit', sa.Integer(), nullable=True),
    sa.Column('is_earn_back', sa.Integer(), nullable=True),
    sa.Column('is_customer_satisfaction_report', sa.Integer(), nullable=True),
    sa.Column('customer_satisfaction_form', sa.Integer(), nullable=True),
    sa.Column('governance_type', sa.Integer(), nullable=True),
    sa.Column('governance_often', sa.Integer(), nullable=True),
    sa.Column('key_personnel', sa.Integer(), nullable=True),
    sa.Column('supplier_personnel', sa.Integer(), nullable=True),
    sa.Column('customer_personnel', sa.Integer(), nullable=True),
    sa.Column('planned_negotiation_month', sa.Integer(), nullable=True),
    sa.Column('negotiations_month', sa.Integer(), nullable=True),
    sa.Column('sole_sourced', sa.Integer(), nullable=True),
    sa.Column('proposed_period_weeks', sa.Integer(), nullable=True),
    sa.Column('actual_period_weeks', sa.Integer(), nullable=True),
    sa.Column('is_due_diligence_completed', sa.Integer(), nullable=True),
    sa.Column('agreement_party', sa.Integer(), nullable=True),
    sa.Column('type_of_service', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Integer(), nullable=True),
    sa.Column('service_credit_cap_type', sa.Integer(), nullable=True),
    sa.Column('service_level_cap_percentage', sa.Numeric(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('ccode', sa.String(length=8), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bespoke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('contract_value_usd', sa.Numeric(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_filler', sa.Integer(), nullable=True),
    sa.Column('to_date', sa.DateTime(timezone=255), nullable=True),
    sa.Column('is_transition_completed', sa.Integer(), nullable=True),
    sa.Column('is_transition_charges_paied', sa.Integer(), nullable=True),
    sa.Column('is_transformation_completed', sa.Integer(), nullable=True),
    sa.Column('missed_kpi', sa.Integer(), nullable=True),
    sa.Column('missed_service_level', sa.Integer(), nullable=True),
    sa.Column('moved_service_level', sa.Integer(), nullable=True),
    sa.Column('payable_service_credits', sa.Integer(), nullable=True),
    sa.Column('paied_service_credits', sa.Integer(), nullable=True),
    sa.Column('is_paied_passed', sa.Integer(), nullable=True),
    sa.Column('pay_back', sa.Numeric(), nullable=True),
    sa.Column('is_customer_satisfaction_report', sa.Integer(), nullable=True),
    sa.Column('customer_satisfaction_result', sa.Integer(), nullable=True),
    sa.Column('is_governance', sa.Integer(), nullable=True),
    sa.Column('is_governance_minute', sa.Integer(), nullable=True),
    sa.Column('is_additional_governance', sa.Integer(), nullable=True),
    sa.Column('additional_governance_cause', sa.Integer(), nullable=True),
    sa.Column('is_formal_notices', sa.Integer(), nullable=True),
    sa.Column('formal_notices_about', sa.Integer(), nullable=True),
    sa.Column('formal_notices_type', sa.Integer(), nullable=True),
    sa.Column('initiated_CCNs', sa.Integer(), nullable=True),
    sa.Column('signed_CCNs', sa.Integer(), nullable=True),
    sa.Column('signed_CCNs_type', sa.Integer(), nullable=True),
    sa.Column('key_personnel_changed', sa.Integer(), nullable=True),
    sa.Column('supplier_personnel_changed', sa.Integer(), nullable=True),
    sa.Column('customer_personnel_changed', sa.Integer(), nullable=True),
    sa.Column('invoiced_charges_usd', sa.Numeric(), nullable=True),
    sa.Column('is_not_invoiced', sa.Integer(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_filler'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_payment', sa.Integer(), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=255), nullable=True),
    sa.Column('charges', sa.Numeric(), nullable=True),
    sa.Column('is_paied', sa.Integer(), nullable=True),
    sa.Column('CREATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_BY', sa.Integer(), nullable=True),
    sa.Column('UPDATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('CREATED_AT', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['is_paied'], ['questionnaire.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestone')
    op.drop_table('user_project')
    op.drop_table('questionnaire')
    op.drop_table('contract_value')
    op.drop_table('bespoke')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
